force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/lwcController.cls
public with sharing class lwcController {
    
    @AuraEnabled(cacheable=true)
    public static List<Team__c> team(){
        List <Team__c> team = new List<Team__c>();
        try {

            team = [Select Id, Name from Team__c  LIMIT 10000];
            return team;
            
        } catch (Exception e) {
            return team;
        }
    }

    @AuraEnabled(cacheable = true)
    public static List<Team_Member__c> teamMember(String TeamId){
        
        List <Team_Member__c> teamMember = new List<Team_Member__c>();
        try {
            String query ='SELECT Id, Name, Skills__c, Team__c, Team__r.Name From Team_Member__c ';
            if(!String.isBlank(TeamId)){
                query = query + 'WHERE Team__c = \''+ TeamId + '\' ';
            }
            query = query + '  LIMIT 10000 ';
            teamMember = database.query(query);
            System.debug(query);
            return teamMember;
        } catch (Exception e) {
            return teamMember;
        }
    }
}